django/databases101/airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),  
    path('', include("users.urls")),    # default home page
]

django/databases101/airline/flights/urls.py
from django.urls import path

from . import views

app_name = "flights"

urlpatterns = [
    path("", views.index, name="index"),
    path("flights/<int:flight_id>", views.flight, name="flight"),
    path("<int:flight_id>/add_passenger", views.add_passenger, name="add_passenger"),
]

django/databases101/airline/users/urls.py
from django.urls import path, include

from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name="index"),
    path('login',views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('redirect-to-flights', views.redirect_to_flights, name="redirect_to_flights")
]

django/databases101/airline/flights/models.py
from django.db import models

# Create your models here.
# Reference Model
class Airport(models.Model):
    code = models.CharField(max_length=5)
    city = models.CharField(max_length=72)
    
    def __str__(self):
        return f"{self.city} ({self.code})"


# Related Model - origin, destination
# Reference Model - Passenger
class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals")
    duration = models.IntegerField()

    def __str__(self):
        """string for representing the flight information within a query set"""
        return f"Flight HHF{self.id} : {self.origin} To {self.destination}, {self.duration} minutes"
    

# Related Model - Flight
class Passenger(models.Model):
    fname = models.CharField("FirstName", max_length=64)
    lname = models.CharField("LastName", max_length=64)
    flight = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self):
        return f"{self.fname} {self.lname}"

django/databases101/airline/users/models.py
from django.db import models

# Create your models here.

django/databases101/airline/flights/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Flight, Passenger

# Create your views here.
def index(request):
    return render(request, "flights/index.html", {"flights": Flight.objects.all()})


def flight(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    passengers = flight.passengers.all()
    non_passengers = Passenger.objects.exclude(flight=flight).all()

    return render(request, "flights/flight.html", context={
        "flight": flight,
        "passengers": passengers,
        "non_passengers": non_passengers,
        })


def add_passenger(request, flight_id):
    if request.method == "POST":
        # retrieve flight details
        flight = Flight.objects.get(pk=flight_id)

        # retrieve passenger_id from POST request
        passenger_id = int(request.POST["passenger"])
        passenger = Passenger.objects.get(pk=passenger_id)
        
        # add passenger to flight
        passenger.flight.add(flight)

        # redirect to modified flight page
        return HttpResponseRedirect(reverse("flights:flight", args=(flight_id,)))

django/databases101/airline/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import authenticate, login, logout

# from django.contrib.sessions.models import Session
# Sessions - 
# - useful to separate user's data
# - for ex. ecommerce store- each session can consist data about 
#   - user profile, user cart items, user checkout

# create views here
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    else:
        return render(request, "users/home.html")
    

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            
            # create user session
            request.session['username'] = user.username

            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, "users/login.html", context={
                "message" : """
                            Invalid Credentials.
                            Are you sure you entered correct Username/Password ?
                            """,
            })
        
    else:
        return render(request, "users/login.html")


def logout_view(request):
    logout(request=request)

    # clear user session
    request.session.clear()

    return render(request, "users/login.html", context={
        "message" : """
                    Logged out successfully!
                    """
    })


def redirect_to_flights(request):
    return redirect(reverse('flights:index'))

django/databases101/airline/flights/templates/flights/flight.html
{% extends "flights/layout.html" %}

{% block content %}
    <h1>Flight HHF{{flight.id}}</h1>
    <ul>
        <li><b>Origin</b> : <br>{{flight.origin}} </li><br>
        <li><b>Destination</b> : <br> {{flight.destination}}</li><br>
        <li><b>Duration</b> : <br> {{flight.duration}} minutes</li><br>
    </ul>
    <h1>Passengers</h1>
    <ul>
        {% for passenger in passengers %}
            <li>{{ passenger }}</li>
            {% empty %}
            <li>No Passengers.</li>
        {% endfor %}
    </ul>

    <h2>Add Passengers</h2>
    <form action="{% url 'flights:add_passenger' flight.id %}" method="POST">
        {% csrf_token %}
        <select name="passenger">
            {% for passenger in non_passengers %}
                <option value="{{ passenger.id }}"> {{ passenger }} </option>
            {% endfor %}
        </select>
        <input type="submit" value="Add Passenger">
    </form>

    <br>

    <a href="{% url 'flights:index' %}">Back To all Flights</a>

{% endblock %}

django/databases101/airline/flights/templates/flights/index.html
{% extends "flights/layout.html" %}


{% block content %}
    <h1>Flights</h1>
    <ul>
        {% for flight in flights %}
            <li><a href="{% url 'flights:flight' flight.id %}">Flight HHF{{flight.id}}</a> : {{flight.origin}} To {{flight.destination}}</li>
        {% endfor %}
    </ul>
    <div><a href="{% url 'users:index' %}">Back To Profile</a></div>
{% endblock %}

django/databases101/airline/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flights</title>
</head>
<body>
    {% block content %}   
    {% endblock %}    
</body>
</html>

django/databases101/airline/users/templates/users/home.html
{% extends "users/layout.html" %}

{% block content %}

    <h1>Home</h1>
 
    <h2>Welcome {{ request.user.first_name }}</h2>

    <h3>Your Information</h3>
    <ul>
        <li>Name : {{ request.user.first_name }} {{ request.user.last_name }} </li>
        <li>Email : {{ request.user.email }} </li>
    </ul>
    <h3>Check Flights</h3>
        <li><a href="{% url 'users:redirect_to_flights' %}">All Flights</a></li>
        <br>
        <div><a href="{% url 'users:logout' %}">Log Out</a></div>
        
{% endblock %}

django/databases101/airline/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
</head>
<body>

    {% block content %}
    {% endblock %}
    
</body>
</html>

django/databases101/airline/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block content %}

    <h1>Login</h1>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    
    <br>

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text", name="username", placeholder="Username">
        <input type="password", name="password", placeholder="Password">
        <br>
        <input type="submit", value="Log In">
    </form>

{% endblock %}